/** Framer CDN assets (first four URLs are shared site chrome; omitted). */
export const NORA_IMAGES = [
  "https://framerusercontent.com/images/UgOzIwMVXWuVaUKZq3zL499dd0.png",
  "https://framerusercontent.com/images/eEmGQPi2zCtjrCcWrW9QWo9wuk4.png",
  "https://framerusercontent.com/images/Xrlp0XIrsZ4ptCTp5Po7AV39zI.png",
  "https://framerusercontent.com/images/HMFqHkOBtiIcgeN2tthpMFKdA.png",
  "https://framerusercontent.com/images/gVkRtPpfAOFF99TqJ6yfSn320.png",
  "https://framerusercontent.com/images/rik8r71BOkweK193HPaui6NLBo.png",
  "https://framerusercontent.com/images/CXG8d1beEWdgrCGvw2NMq8b2u0.png",
  "https://framerusercontent.com/images/gLZPJtJAEbqDKV4dEt9Cs8OAt8.png",
  "https://framerusercontent.com/images/bpXZFehoMQSdd3dFvvyNVZJbDM.png",
  "https://framerusercontent.com/images/6tTbkXggWgQCAJ4DO2QEdXXmgM.svg",
  "https://framerusercontent.com/images/11KSGbIZoRSg4pjdnUoif6MKHI.svg",
  "https://framerusercontent.com/images/xbiYjhZ61jVlDuysnhb5yK9Sc.png",
  "https://framerusercontent.com/images/4kCDYOYu1Nh91dXbwKSKaSCCk.png",
  "https://framerusercontent.com/images/4sfKJoaUhMMhs9mxVSXRZM7EvL0.png",
  "https://framerusercontent.com/images/lDYBJ33NL4lF03dJSpTVFIATyHM.png",
  "https://framerusercontent.com/images/SkutrdLbOmFfINSIlkbAl0j3fs.png",
  "https://framerusercontent.com/images/LqKQKtlzq5auvc1UnxTiP96y4.png",
  "https://framerusercontent.com/images/VEsmgEd1QyGcQOHVkb46En5Svw.png",
  "https://framerusercontent.com/images/sLX8XI45hJXUp0259QNtiDNt24.png",
  "https://framerusercontent.com/images/tTbRqVNfi7vEdx13gDtLCjfYNx8.png",
  "https://framerusercontent.com/images/LWuY7wj7vu16PWBozGdmysSzY.png",
  "https://framerusercontent.com/images/fcyxjrBuCZ4kOXlQXvRCDIA7V0w.png",
  "https://framerusercontent.com/images/VJeamTCvKIaJYUZozHdISsxkVo.png",
  "https://framerusercontent.com/images/W6xZuTF7QOyl3VmXkf07WhRAxpM.png",
  "https://framerusercontent.com/images/HqsZgg5uijvQPduqIv3KEM8vU7Y.png",
  "https://framerusercontent.com/images/GmWHGY0KIe4KnpEdhTm2yRDvYo.png",
  "https://framerusercontent.com/images/NqrWUotD4K2Q91ABwsWucFZuQU.png",
  "https://framerusercontent.com/images/pDtEHNDfwonPvEUqWDSwzkPvpUM.png",
] as const;

export const SIGN_IMAGES = [
  "https://framerusercontent.com/images/CawPPv5mW33sdboTmZzJLrHReg0.png",
  "https://framerusercontent.com/images/chMTMRrxeDSFvgPBYfnfNLMKQFg.png",
  "https://framerusercontent.com/images/5JgTste0elxKcdh3x0EhK4GX3iY.png",
  "https://framerusercontent.com/images/uX3eZJ8CGgfCFDuSmUUSAg4xeY.png",
  "https://framerusercontent.com/images/BfZDMrhIZcG2gMa8e9W6cV5es1U.png",
  "https://framerusercontent.com/images/mV6l4aO9rp78FRY1T65CC2Ig0xg.png",
  "https://framerusercontent.com/images/nMiWaYCR38j2DaXN11C5MOsTE.png",
  "https://framerusercontent.com/images/VACk2thY2O78Bnz6ZDR2A7Xmrw.png",
  "https://framerusercontent.com/images/RgNetN7aP67pWuRLcNwE3Jxygs8.png",
  "https://framerusercontent.com/images/sj3sjmApKI615H4s03Vs13dKGWs.png",
  "https://framerusercontent.com/images/oTmVWyb7CFemChQGDy76iEeFzQ.png",
  "https://framerusercontent.com/images/YtKNF7c4mZNTMLsuIwH7LMKRGI.png",
  "https://framerusercontent.com/images/GaqsG22POmajMgURqmO8IxWMtc.png",
  "https://framerusercontent.com/images/ajvoR4c212QLRxpwjsG1UVhvrU.png",
  "https://framerusercontent.com/images/4D3Km2FlNXeYuTtNPKyLASGfaig.png",
  "https://framerusercontent.com/images/iU1lnejjtclsBL4fRFnezem8YAw.png",
  "https://framerusercontent.com/images/SngOjNFJ07A3FlopfE4A2umqPs.png",
  "https://framerusercontent.com/images/CvJOWgGKTOxyTYghgTxXE0x09o.png",
  "https://framerusercontent.com/images/lyLgHdDhiTMtd0975fU5zKFiouU.png",
  "https://framerusercontent.com/images/V47xUrDbdA372STZaFET8RSolHU.png",
] as const;

export const HONEY_IMAGES = [
  "https://framerusercontent.com/images/66BsUXsap4Zw44Milhx1WcEMnU.png",
  "https://framerusercontent.com/images/6m6KQfZIMg9cfdk316yKoNR6rWY.png",
  "https://framerusercontent.com/images/63nSUdv1oNrrQU6BR9fcWNM8hYE.png",
  "https://framerusercontent.com/images/vQDIJOA8D5bQfUZaL98KTUfDFQ.png",
  "https://framerusercontent.com/images/2tHAXLeRLvit9zupMl2cwLjZ80.png",
  "https://framerusercontent.com/images/u0xrtcMpVgYrTY7MtPiSi9UkA.png",
  "https://framerusercontent.com/images/rkfko06v1ChlRBxBPFYATRpL7HQ.png",
  "https://framerusercontent.com/images/dDVwZu97D88uTpSmeHX6o0uM5kk.png",
  "https://framerusercontent.com/images/sjO3ZPigpUAPzUaElSMn2uN0r2I.png",
  "https://framerusercontent.com/images/xfNLJSUUYKU6MbNHBbKxMQKeAe0.png",
  "https://framerusercontent.com/images/1w1kuHb9YIIZuyJ6Juv8F45IQ.png",
  "https://framerusercontent.com/images/kvGBFbObVhc28RcUQBBKH1oXN0.png",
  "https://framerusercontent.com/images/0DEI8h9cyxgjuYgSkoDValTdqMo.png",
] as const;
